/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.PVEReport;
import server.PVEReportDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author xavier
 */
public class Main extends javax.swing.JFrame {
    private PVETableModel pvemodel = new PVETableModel();
    private PVEReport selectedPVEReport = null;
    private List<PVEReport> getallreportsonce = null;
    private List<PVEReport> reports = null;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        try {
            getallreportsonce = PVEReportDAO.getReports();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tblPVEReports.setModel(pvemodel);
        tblPVEReports.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //tblPVEReports.getSelectionModel().addListSelectionListener(new PVERowSelectionListener());
        cboItems.setVisible(false);
        fillCbo();
        fillPVETableAll();
    }
    
    private void fillCbo()
    {
        String oldName = "";
        int oldAccount = 0;
        for (PVEReport pve: getallreportsonce){
            if (!pve.getKillerName().equals(oldName) )
            {
               cboKillerNames.addItem(pve.getKillerName());
                oldName = pve.getKillerName(); 
            }
            
            if (pve.getKillerAccount() != oldAccount){
                cboKillerAccount.addItem(pve.getKillerAccount());
                oldAccount = pve.getKillerAccount();
            }
            
        }
    }

    private void fillPVETableAll()
    {
        for (PVEReport pve : getallreportsonce) {
            selectedPVEReport = null;
            pvemodel.getReports().add(pve);
        }
        pvemodel.fireTableDataChanged(); 
    }
    
    private void fillPVETable(int accountId)
    {
        for (PVEReport pve : getallreportsonce) {
            //cboTrekkingen.addItem(t);
            selectedPVEReport = null;
            //pvemodel.getReports.add(pve);
        }
        pvemodel.fireTableDataChanged();
    }
    
    public PVETableModel getpvemodel() {
        return pvemodel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboKillerNames = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboKillerAccount = new javax.swing.JComboBox();
        cboItems = new javax.swing.JComboBox();
        lblTotalReports = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPVEReports = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("deathknell.cc");

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setName(""); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jLabel1.setText("FILTERS");

        jLabel2.setText("KillerName");

        cboKillerNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- All Names --" }));
        cboKillerNames.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKillerNamesItemStateChanged(evt);
            }
        });

        jLabel3.setText("KillerAccount");

        cboKillerAccount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- All Accounts --" }));
        cboKillerAccount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKillerAccountItemStateChanged(evt);
            }
        });

        cboItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- All Items --", "16345", "23467", "500000", "500001", "500002" }));
        cboItems.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboKillerNames, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboKillerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboItems, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalReports, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKillerNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cboItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboKillerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalReports))
                .addGap(22, 22, 22))
        );

        tblPVEReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "KillerName", "KillerGuid", "KillerAccount", "ItemEntry", "ItemGuid", "KilledName", "KilledGuid", "KilledAccount", "AreaId", "ZoneId"
            }
        ));
        tblPVEReports.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tblPVEReports);
        tblPVEReports.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PVE_REPORTS", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboKillerNamesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKillerNamesItemStateChanged
        // TODO add your handling code here:
        reports = null;
        pvemodel.getReports().clear();
        cboKillerAccount.setSelectedIndex(0);
        int totalReports = 0;
        
        for (PVEReport pve : getallreportsonce) {
            if (cboKillerNames.getSelectedIndex() == 0){
                pvemodel.getReports().add(pve);
                totalReports +=1;
            }
            else
            {
                if (pve.getKillerName().equals(cboKillerNames.getSelectedItem())){
                     pvemodel.getReports().add(pve);
                     totalReports +=1;
                }
            }            
        }
        pvemodel.fireTableDataChanged();
        lblTotalReports.setText("Total reports: " +totalReports);
    }//GEN-LAST:event_cboKillerNamesItemStateChanged

    private void cboKillerAccountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKillerAccountItemStateChanged
        // TODO add your handling code here:
        reports = null;
        pvemodel.getReports().clear();
        cboKillerNames.setSelectedIndex(0);
        int totalReports = 0;
        
        for (PVEReport pve : getallreportsonce) {
            if (cboKillerAccount.getSelectedIndex() == 0){
                pvemodel.getReports().add(pve);
                totalReports +=1;
            }
            else
            {
                if(Integer.toString(pve.getKillerAccount()).equals(cboKillerAccount.getSelectedItem().toString())){                    
                    pvemodel.getReports().add(pve);
                    totalReports +=1;
                }
            }
        }
        pvemodel.fireTableDataChanged();
        lblTotalReports.setText("Total reports: " +totalReports);
    }//GEN-LAST:event_cboKillerAccountItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboItems;
    private javax.swing.JComboBox cboKillerAccount;
    private javax.swing.JComboBox cboKillerNames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotalReports;
    private javax.swing.JTable tblPVEReports;
    // End of variables declaration//GEN-END:variables
}
