INSERT INTO `command` (`name`, `permission`, `help`) VALUES 
('custom', 1001, 'Syntax: .custom Display custom commands'),
('custom hallo', 1002, 'test'),
('custom object', 1003, 'Syntax: .custom object $objname\r\n\r\nLooks up a NORMAL gameobject by $objname, and returns all matches with their Gameobject ID\'s'),
('custom patch', 1004, 'Syntax: .custom patch $objname\r\n\r\nLooks up a custom PATCH gameobject by $objname, and returns all matches with their Gameobject ID\'s'),
('eventgm', 1020, 'Syntax: event $subcommand'),
('custom mass revive', 1011, 'Syntax: .massrevive\r\n\r\nRevive the selected group. If no player is selected, it will hopefully revive your own group.'),
('eventgm addtoken', 1021, 'Syntax: eventgm addtoken $amount\r\n\r\nAdd $amount event tokens to the selected player.'),
('custom mass unaura', 1012, 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.'),
('custom mass', 1010, 'Syntax: mass $subcommand'),
('eventgm unaura', 1022, 'Syntax: .unaura'),
('custom mass morph', 1013, 'Syntax: .mass morph #displayid\r\n\r\nChange your target\'s group current model id to #displayid.'),
('custom mass demorph', 1014, 'Syntax: .demorph\r\n\r\nDemorph the selected playergroup.'),
('headgm', 1030, 'Syntax: headgm $subcommand'),
('headgm addgm', 1031, 'Syntax: .headgm addgm $playername $"comment between quotes"\r\n\r\nAdds $playername to the GMtable with $"quotedtext in comment"');
