INSERT INTO `command` (`name`, `security`, `help`) VALUES 
('eventgm', 2, 'Syntax: event $subcommand'),
('mass revive', 2, 'Syntax: .massrevive\r\n\r\nRevive the selected group. If no player is selected, it will hopefully revive your own group.'),
('eventgm addtoken', 2, 'Syntax: eventgm addtoken $amount\r\n\r\nAdd $amount event tokens to the selected player.'),
('custom mass unaura', 2, 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.'),
('custom mass', 2, 'Syntax: mass $subcommand'),
('eventgm unaura', 2, 'Syntax: .unaura'),
('custom mass morph', 2, 'Syntax: .mass morph #displayid\r\n\r\nChange your target\'s group current model id to #displayid.'),
('custom mass demorph', 2, 'Syntax: .demorph\r\n\r\nDemorph the selected playergroup.'),
('headgm', 3, 'Syntax: headgm $subcommand'),
('headgm addgm', 3, 'Syntax: .headgm addgm $playername $"comment between quotes"\r\n\r\nAdds $playername to the GMtable with $"quotedtext in comment"'),
('custom', 3, 'Syntax: .custom Display custom commands'),
('custom hallo', 0, 'test'),
('custom object', 3, 'Syntax: .custom object $objname\r\n\r\nLooks up a NORMAL gameobject by $objname, and returns all matches with their Gameobject ID\'s'),
('custom patch', 3, 'Syntax: .custom patch $objname\r\n\r\nLooks up a custom PATCH gameobject by $objname, and returns all matches with their Gameobject ID\'s');
