INSERT INTO `rbac_permissions` (`id`, `name`) VALUES 
(1001, 'RBAC_PERM_COMMAND_CUSTOM'),
(1002, 'RBAC_PERM_COMMAND_CUSTOM_OBJECT'),
(1003, 'RBAC_PERM_COMMAND_CUSTOM_HALLO'),
(1004, 'RBAC_PERM_COMMAND_CUSTOM_PATCH'),
(1010, 'RBAC_PERM_COMMAND_CUSTOM_MASS');
(1011, 'RBAC_PERM_COMMAND_CUSTOM_MASS_REVIVE'),
(1012, 'RBAC_PERM_COMMAND_CUSTOM_MASS_UNAURA'),
(1013, 'RBAC_PERM_COMMAND_CUSTOM_MASS_MORPH'),
(1014, 'RBAC_PERM_COMMAND_CUSTOM_MASS_DEMORPH'),
(1020, 'RBAC_PERM_COMMAND_EVENTGM'),
(1021, 'RBAC_PERM_COMMAND_EVENTGM_ADDTOKEN'),
(1022, 'RBAC_PERM_COMMAND_EVENTGM_UNAURA'),
(1030, 'RBAC_PERM_COMMAND_HEADGM'),
(1031, 'RBAC_PERM_COMMAND_HEADGM_ADDGM');
